---
- name: Update package cache
  become: true
  ansible.builtin.apt:
    update_cache: true

- name: Upgrade packages
  become: true
  ansible.builtin.apt:
    upgrade: dist
    autoremove: true
    autoclean: true
