---
- name: Debian Laptop Playbook
  hosts: hosts
  become: true

  roles:
    - role: updates
      tags:
        - updates

    - role: install
      tags:
        - install

    - role: git
      tags:
        - git

    - role: backup
      tags:
        - backup

